name: Plots
author: pongy20, marcelm19t
version: 1.0.1
main: de.plots.main.main
commands:
     plot:
          description: Type /plot help to all Commands
     admin:
          description: This is a Admin command